### ISSUE TITLE
Could not find credentials for me-central-1 region

### ISSUE THREAD

**Issue by fayas-akram** [jenkinsci/amazon-ecr-plugin#171]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
CLOUD: AWS
ENV: Production
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

amazon linux 2. 

### Reproduction steps

1.  Add build steps for UAE region and try to login ECR
```docker.withRegistry('https://xxxxxx.dkr.ecr.me-central-1.amazonaws.com', 'ecr:me-central-1:xxxxxxx') {}```

### Expected Results

Success

### Actual Results

ERROR: Could not find credentials matching ecr:me-central-1:XXXXXX

### Anything else?

the plugging works with other regions. it fails for me-central-1 region

### Are you interested in contributing a fix?

Yes

**Comment by TobiX** [comment]
Looks like #31?

**Comment by Tesseract99** [comment]
If I am not wrong,this issue comes when the credentials you have declared in Jenkins / credentials section are NOT of kind "AWS credentials". But, of some other type like - "username and password"

**Comment by TobiX** [comment]
Closing due to missing information. Feel free to reopen if the issue persists.
