### ISSUE TITLE
withRegistry() throws error when pushing to region eu-north-1

### ISSUE THREAD

**Issue by vietnguyen1254** [jenkinsci/amazon-ecr-plugin#31]
Hi,

I want to push the docker image into an ECR repository, and the docker.withRegistry() throws  following error,

`ERROR: Could not find credentials matching ecr:eu-north-1:dev-aws-keys`

Code snippet: 

`docker.withRegistry('https://1234567890.dkr.ecr.us-east-1.amazonaws.com', 'ecr:eu-north-1:demo-ecr-credentials') {     docker.image('demo').push('latest')   }`

Can you help please help me out?

**Comment by TobiX** [comment]
Closing due to missing information. Feel free to reopen if the issue persists.
